## all workflow of github-action !
name: CI

on:
  push:
    branches: [advanced]
  


jobs:
  frontend:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v6
        with: 
          node-version: '26'
          cache: npm
          cache-dependency-path: './frontend/package-lock.json'

          check-latest: false

      - name: install package
        run: npm ci 
        working-directory: ./frontend

      - name: Run Linter
        run: npm run lint
        working-directory: ./frontend

      - name: Run Test Cases
        run: npm test
        working-directory: frontend


      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags:  ${{ vars.DOCKERHUB_USERNAME }}/devboard-forntend:v1.0.0

  backend:


    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v7


      - name: Setup Go #backend
        uses: actions/setup-go@v6
        with: 
          go-version: '1.23'
          go-version-file: 'go.mod'
          cache: true
          check-latest: false
          cache-dependency-path: 'go.sum'

      - name: formating go code
        run: go fmt
        working-directory: backend

      - name: test cases
        run: go test
        working-directory: backend


      - name: Run go vet
        run: go vet
        working-directory: backend

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags:  ${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:v1.0.0

  deployment:

     needs: [frontend,backend]
     uses: ./.github/workflows/cd.yml
     secrets: inherit






      
      


