name: DevSecOps_Security

on:
 push:
  branches:
    - devsecops_practice


    
jobs:

        code_quality:
          uses: ./.github/workflows/code_quality.yml


        secret_scanning:
          uses: ./.github/workflows/secret_scanning.yml

        
        dependency_scan:
         uses: ./.github/workflows/Dependency_scan.yml

        docker_scanning:
          uses: ./.github/workflows/docker_scanning.yml
          secrets: inherit

        sonar_Quebe:
           uses: ./.github/workflows/sonarQube_scanner.yml
           secrets: inherit

        
        code_test_cases:
           uses: ./.github/workflows/code_test.yml

        
        docker_push:
          uses: ./.github/workflows/docker_push.yml
          needs: [code_quality,secret_scanning,dependency_scan,docker_scanning,code_test_cases,sonar_Quebe]
          secrets: inherit


        deploy:
         uses: ./.github/workflows/deploy.yml
         needs: [docker_push]
         secrets: inherit