name: DevSecOps_Security

on:
 push:
  branches:
    - devsecops_practice


    
jobs:

        code_quality:
          uses: ./.github/workflows/code_quality.yml


        secret_scanning:
          uses: ./.github/workflows/secret_scanning.yml

        
        dependency_scan:
         uses: ./.github/workflows/Dependency_scan.yml