name: docker_scanning

on:
 workflow_call:
   
jobs:
  
 docker_scan:

  runs-on: ubuntu-latest

  steps:

   - name: checkout code
     uses: actions/checkout@v7

   - name: Run Hadolint Linter
     uses: hadolint/hadolint-action@v3.1.0
     with:
      dockerfile: ./frontend/Dockerfile

   - name: Run Hadolint Linter
     uses: hadolint/hadolint-action@v3.1.0
     with:
       dockerfile: ./frontend/Dockerfile